### ISSUE TITLE
Common gomqtt organisation on GitHub.

### ISSUE THREAD

**Issue by 256dpi** [gomqtt/organisation#1]
Hi @alsm, @zhenjl, @steakknife, @plucury

You all are heavily involved in working on MQTT related libraries and components for the Go programming language. Until now I have been involved mostly in the node and javascript community over at https://github.com/mqttjs. But as I am more and more using Go for projects like shiftr.io, I wished there would be the same community that works together and maintains these components.

Today MQTT for Go is scattered among various projects. There are several implementations of encoders/decoders, client libraries and frameworks for building brokers. As I do not want to create another project that does the same thing, I hereby try to get these projects together and start building **one** encoder/decode, **one** client library and **one** server framework. I'm certain that if we work together, we can improve the quality of these components and inhibit the copy-and-modify approach.

I know that this will not be an easy task, so please add your feedback and hopefully we can work on this together!

**Comment by 256dpi** [comment]
@jeffallen, @yosssi: same goes for you, please share your opinion!

**Comment by jeffallen** [comment]
I agree that getting all Go MQTT stuff in one place would be a good idea. Look at the fork history of my package. https://github.com/jeffallen/mqtt/network There are several users and people have started adding features without sending PRs to me. @zwczou @ninjasphere @bnham is it time to get all MQTT stuff in one place? Let's do it... respecting existing licenses, of course!

**Comment by 256dpi** [comment]
I also want to add @huin to the discussion.

@jeffallen Cool to have you on board!

**Comment by plucury** [comment]
It's cool. I'd like to participate in.

**Comment by huin** [comment]
Heh, I completely forgot I (re)wrote a library for part of MQTT. It seems to have been starred a few times.

I'm happy to mark it as deprecated and direct people towards a more collaborative effort in my own repo.

**Comment by zhenjl** [comment]
There's also http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.golang.git/ which is a client lib for Go.

Happy to discuss further about this effort. Seems like the right thing to do.

I was just thinking about restarting some dev work on surgemq (and just reclaimed surgemq.com from the redemption pool after a user reminded me that the website was down.)

**Comment by 256dpi** [comment]
Thanks for the support guys!

In the next step, we would have to decide which project we take as a base for the gomqtt project. 

Working with the eclipse Paho implementation tends to be complicated, as they do not allow GitHub for code hosting. @alsm: Any comments on that?

So right now, I see the following possibilities:

1. Continue the encoder/decoder project of @huin and @plucury (are they still compatible?) With that foundation we could split @jeffallen's project into a client library and small server framework.

2. With @zhenjl permission we could extract the encoder/decoder of hist project, as well was the client implementation and the middleware to build a server. @zhenjl: I guess you want to focus on your server implementation anyway?

3. Is there another one?

Maybe the individual project owners could also share shortly the state of their project and for example how well the each have implemented the official specification, etc.

**Comment by huin** [comment]
It's been ages since I put up my fork of the mqtt encoder/decoder library, and I don't think I ever actually used it - probably just did it for the fun of doing that fiddly network protocol stuff.

I *believe* it conformed to the mqtt standard at the time, but I likely didn't ever test it against any other implementations, other than its own unit tests. In theory it looks like it supports both framed and streaming payload modes of operation.

**Comment by bnham** [comment]
I realize that I got on this thread because I forked gomqtt last year and
made some tiny changes to it in my local fork. To be honest, I have
absolutely no recollection of making those changes, and based on a quick
glance at them, I'm pretty sure the few small commits I made were just
non-functional WIP commits before I had to abandon the project because we
decided to re-use an existing MQTT server that we were already running
elsewhere in the org rather than writing a new Go MQTT server.

I'll close down my fork to limit the confusion. Best of luck with the new
organization.

Ben

**Comment by jeffallen** [comment]
The client and server I wrote supports only best effort delivery. It does
not write to stable store. It is not optimized for raw speed like Jian's
is. It is basically textbook Go, with one goroutine per connection, and
messages passed via channels.

Keeping the commit history of a project is important. So please don't try
to break up the clients and servers into different repos, it all uses the
save code on the backend anyway.

I will not be able to work on this in the coming months, but I agree that
the message encoder and the clients and servers should all be in the same
org, so you should feel free to move ahead with your proposal. When it's
up, I will change my repo to point people at the canonical one.

**Comment by zhenjl** [comment]
Here's my status from the dec blog post:

Features, Limitations, and Future
Features

Supports QOS 0, 1 and 2 messages
Supports will messages
Supports retained messages (add/remove)
Pretty much everything in the spec except for the list below
Limitations

All features supported are in memory only. Once the server restarts everything is cleared.
However, all the components are written to be pluggable so one can write plugins based on the Go interfaces defined.
Message redelivery on reconnect is not currently supported.
Message offline queueing on disconnect is not supported. Though this is also not a specific requirement for MQTT.
Future

Message re-delivery (DUP)
$SYS topics
Server bridge
Ack timeout/retry
Session persistence
Better authentication modules

Thx

Jian

**Comment by 256dpi** [comment]
@jeffallen As server implementations are in most cases very specific and the client library isn't it makes more sense to deal with them separately. Also in the node.js organization we ended up splitting one repository into the encoder/decoder, a fully-compliant client library and some abstractions for custom-broker implementations. That way everyone was happy. **Of course we don't need to remove the whole git history, maybe we could just duplicate the repos and focus on these parts separately.**

@zhenjl Thanks for the head-sup! I guess your implementation is straight-forward and would be a good starting point. **Would you be generally up to contribute these basic parts of your project to this organization and maybe also allow slight License changes to make it even more open?** As the organizations focus should not be on developing a broker, it would not compete your project. But as I'm looking for a good foundation for my project, I'd like to contribute something that stays open and maintained by a community.

**Comment by zhenjl** [comment]
I am w/ @jeffallen on the server/client libs. For example, surgemq's server and client implementations are just basic containers for the "service" struct, which implements almost all of the logics that are shared by server and client. So in surgemq, there's

- "service" that implements MQTT service-related logic
- "message" that implements encoding/decoding
- "session" that implements session-related logic like a session store
- "client" which is just a thin wrapper around "service"
- "server" which is a wrapper containing a list of "services" (one per client)

**Comment by 256dpi** [comment]
Ok is see that there has been given much thought on that architecture.

Still, I see the role of the gomqtt organization as a provider of building blocks for go and MQTT related projects. So I just have the feeling that maintaining a project as big as surgemq would totally go beyond the scope. Also these building blocks should not have any opinion on how they are used in a client or server example. The split-up in the node.js community led to some interesting projects that for example experimented with different server architectures (middle-ware based, ultra performance in memory, etc.).

How do you see the shape of these building blocks for the go community?

**Comment by zhenjl** [comment]
@256dpi,

I just looked at the mqttjs org and it seems like the client repo is the most popular (by stars and by contributors). The encoder/decoder has some stars but not that many. This tells me most people are interested in using the client.

i am curious why the JS community didn't rally around the Paho JS client. Is it because of the difficulty to contribute? 

I suppose I can split out the _message_ package as a separate encoder/decoder package. In fact, I had it as a separate _mqtt_ package way back when, and then for some reason decided to merge it into the overall project. I still have back and forth debate myself on whether I should split that out. 

Separately, I can split out a _service_ package that can be used to build clients or servers. And then build a _client_ repo/tool that uses the _service_ package. 

WRT to license, what's the downside of Apache 2, just curious?

**Comment by 256dpi** [comment]
Yes, the client is the most important part for many users. However maybe with go that is different as it is more a system programming language, and people maybe tend to be more interested towards implementing custom brokers.

I remember that there was a discussion, but it ended with the request to move the code to eclipse servers (away from github) which would result in way less contribution.

The mqtt.js implementation is heavily based on node.js' callback style API, where paho.js was (and is still?) focused on browsers.

**Cool, I guess we should start with that and then see which parts are good to follow.** I'll give you admin access to the org, so you can make the split. I suggest the repo name to be `gomqtt/packet`, `gomqtt/encoding` or something like this rather than including `messages`, as this is more related to the MQ paradigm as the protocol's binary packets IMHO.

I don't think that there is a downside, I personally use mostly MIT as it is pretty short. ;) I do however favor the idea of an OPEN open-source project which includes that the copyright belongs to all contributors: https://github.com/mqttjs/MQTT.js/blob/master/LICENSE.md. Would you be able to arrange with that?

Thanks for contributing!

**Comment by 256dpi** [comment]
Nevermind, `gomqtt/message` is also fine, in the spec they use message more than packet.

**Comment by zhenjl** [comment]
To be clear, like @jeffallen,  I don't have time to work on much these days. Full time non-dev gig and family will take precedence. 

I did split out the _message_ package into a separate repo. You have my permission to fork (not that you need it) and modify as you see fit.

I looked to see if there's an easy way to extract the _service_ package but it might take a bit more work than I anticipated. Will have to find time to do that without breaking other things.

I also changed the copyright to The SurgeMQ Authors, copying from the go-mysql-driver repo. I believe that's what you mean by OPEN open-source project. Again, feel free to do as you see fit.

**Comment by 256dpi** [comment]
Ok, no worries, I have time to do that.

Cool, thanks a lot!

I favor copying the repository, a fork always indicates that another repo is upstream, but in this case the idea of the whole thing is that the `gomqtt` has the upstream repositories.

**Comment by jeffallen** [comment]
Keep the history by using Git push to push all the commits into the new
repo. I agree that not forking is a good idea, so send the message that
this is the new main repo.

**Comment by 256dpi** [comment]
@jeffallen Yup, did that. ;)

**Comment by alsm** [comment]
Sorry I'm late to the party, hadn't been checking for a while. I'm interested to see what comes out. The mqtt server I developed is a plaything for my own ideas, and surgemq from @zhenjl is much nicer (and performant). I am also the maintainer for the Eclipse Paho Go client, and that I have a personal commitment to continue doing that. That said we have not had a 1.0 release of that client yet so the API is not fixed, I'm not opposed to syncing into that codebase any client we develop here (although I'd have to check on licensing and attribution issues).

**Comment by 256dpi** [comment]
@alsm Thanks for your reply! With the first release of gomqtt/message the encoding/decoding part has been successfully extracted. Now, the current idea is to first try extracting @zhenjl "service" facility from surgemq as a common "connection" manager thing. Later we can build a nice client API on top of that and even small server frameworks.

I guess we should first see how these things turn out, and then think about the future, also regarding Eclipse. IMHO for the community it would be the best to join forces and build the **best** set of MQTT libraries for go. ;)

**Comment by zhenjl** [comment]
Thanks @alsm for the nice words. As @256dpi said, we split out the message package for now. I am going to work on splitting out the "service" package but that's a bit more work. 

It would actually be great if we, as a community, prioritize the client and server requirements so we have some type of roadmap to develop towards.

**Comment by 256dpi** [comment]
@zhenjl That is a good idea, that way the others can also join and contribute. I'll setup some new issues in this repo for the different parts. I myself will first finish the encoder/decoder by adding a fuzzing test and make sure the parser does not do anything nasty...

I'll officially close this issues, as the problem of a "missing community" has been solved! :)
